### ISSUE TITLE
Adding data to firebase 

### ISSUE THREAD

**Issue by sohilluhar** [nhorvath/Pyrebase4#2] opened 2019-04-09 13:20 UTC
Make sure these boxes are checked before submitting your issue:

[] Check that your version of Python is 3.4+
[] Check that you are on the newest version of Pyrebase
[] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

**Comment by nhorvath** [comment] 2019-04-09 14:02
Yeah, that's just how firebase works, but you can use order by in your application to sort them.
db.child("bookbuddybook").order_by_key().get()

have you tried making the key numbers smaller alphabetically? They are probably sorted as a string, not as a number.

I'm going to close this issue though as it's not a bug and this isn't a firebase help forum.

**Closed by nhorvath** 2019-04-09 14:02 UTC
